name: Node CI

on: [push,pull_request]
jobs:
  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: make foler
        run: mkdir docs
      - name: copy files
        run: cp CNAME index.html docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # default: public